### ISSUE TITLE
pybind unable to convert pycolmap.Reconstruction.points3D

### ISSUE THREAD

**Issue by qchenevier** [colmap/pycolmap#216]
I apologize in advance for the badly formatted issue. In some conda-forge builds of pycolmap, it is not possible to access the attributes of the reconstruction objects: https://github.com/conda-forge/pycolmap-feedstock/issues/14

It seems that this issue is coming from here and it is resolved in the latest commits as stated by a maintainer of the conda-forge feedstock: https://github.com/conda-forge/pycolmap-feedstock/issues/14#issuecomment-1854755308

I'm creating this issue only to share information between repos and to track when the issue will be solved (hopefully with the next release).

(Feel free to close this if you are not happy with that).

**Comment by Tobias-Fischer** [comment]
Hi, I'm the pycolmap maintainer on conda-forge. I am currently in the process of creating a build of pycolmap based on the latest commit on the main branch, as opposed to the latest release. The issue does not exist there. So please ignore here.

**Comment by Tobias-Fischer** [comment]
Hi, it would be amazing if the build frequency could be increased and synced. 

This would help conda-forge a lot, including getting rid of those patches that you refer to (which are mostly pull requests already merged into `main` in colmap/pycolmap).

For colmap, I have released a package based on a recent colmap commit, which only has two minor patches (see https://github.com/conda-forge/colmap-feedstock/tree/dev/recipe). The LZ4 patch is conda-specific on Windows, but should work upstream without issues (happy to create a PR). The boost patch seems like it should actually be upstreamed (otherwise Windows build failed with a missing link error).

For pycolmap, I am currently in the process of releasing a package based on a recent commit, too - just some Windows+CUDA issues to resolve (I saw/use your PR), but there is an issue using scikit-build+win+cuda+conda.

Ideally, the PyPi and conda builds should be able to happily exist side-by-side; if there are more frequent releases here, then the conda-forge feedstock should be a thin wrapper around the repositories here. If the PyPi builds are a big effort for you, I'd be more than happy to add you as maintainers to the conda-forge feedstocks so you can take control there. I'm personally a big fan of conda-forge and maintain >100 repos ..

**Comment by sarlinpe** [comment]
> The [boost patch](https://github.com/conda-forge/colmap-feedstock/blob/dev/recipe/fix-boost-link.patch) seems like it should actually be upstreamed (otherwise Windows build failed with a missing link error).

I believe that this should be fixed by PR https://github.com/colmap/colmap/pull/2304. I'd be great if you could send a PR for LZ4.

> there is an issue using scikit-build+win+cuda+conda.

We use the PyPI build pipeline for continuous testing. Not having the conda pipeline tightly integrated means we currently cannot use it to drive the development. Currently the PyPI pipeline doesn't cover CUDA and osx-arm64, but I'd like it to in the future - though it's low priority for now.

> if there are more frequent releases here, then the conda-forge feedstock should be a thin wrapper around the repositories here

Yes, it would be great to have the feedstock closely track the upstream repos (with frequent releases) so we can catch issues early and minimize discrepancies across wheels. One thing we'll need to unify are build configs - currently we build COLAMP for PyPI wheels without GUI and CGAL to reduce the wheel size.
