### ISSUE TITLE
Windows build instructions and pip wheels

### ISSUE THREAD

**Issue by mihaidusmanu** [colmap/pycolmap#34]

**Comment by MirrorYuChen** [comment]
Hard Core Demand!!!!!!!!

**Comment by Skydes** [comment]
+1, likely the source of some issues/confusions when installing hloc: https://github.com/cvg/Hierarchical-Localization/issues/149 https://github.com/cvg/Hierarchical-Localization/issues/140

**Comment by stevosaurus** [comment]
+1 I would like windows wheels available as well. I am struggling to build the library on windows with the given instructions and latest commit in master.

**Comment by urbste** [comment]
I would highly recommend to use the Ubuntu subsystem WSL 2 this. WSL2 + VSCode with Remote Explorer Extension.

**Comment by ZZWang21** [comment]
> I would highly recommend to use the Ubuntu subsystem WSL 2 this. WSL2 + VSCode with Remote Explorer Extension. In this way you can install and use pycolmap (or rather any Linux only project) on Windows without problems.

what if I use pycolmap on Windows?

**Comment by zr19980402** [comment]
I have got the same error ,  But I cannot find a valid way to solve it. Could you help me?

**Comment by pwais** [comment]
Am attempting to work on this in https://github.com/colmap/pycolmap/pull/114 ...

Dumb question: how are windows users installing pycolmap today?  It seems the windows binary release for COLMAP doesn't necessarily include everything you need... but vcpkg can install it maybe?  Do windows users use vcpkg to install COLMAP?

**Comment by mihaidusmanu** [comment]
I never installed it myself, but most people I know use vcpkg on windows .

Maybe you can take a look at the following guide to compile PyCOLMAP on Windows - https://github.com/colmap/pycolmap/pull/85/files (but I think this way broke at some point)

**Comment by pwais** [comment]
thank you @mihaidusmanu !  I'll keep pushing on vcpkg ...  it looks like part of that recommended path still works 
 https://github.com/pwais/pycolmap/actions/runs/4220906865/jobs/7327625654

**Comment by pwais** [comment]
@mihaidusmanu  FWIW I've messed around some more and now I'm installing COLMAP via `vcpkg`.  I have a modern Core i7 laptop with good internet and it's taking now over 4hrs and still going...  I wonder, do you think the COLMAP maintainers might be open to just building pycolmap wheels as part of their own release?  That's probably a longer conversation... but it would save a bit of build confusion and afford a better tie between pycolmap and colmap releases.  

Thus far I've failed to get Github CI to build a wheel.  It'll run for 4+hours but I'm concerned about running out of minutes on my account.  Other alternatives I'll try:
 * use the Windows binary release plus the source release headers.  I've never tried something like that on _Windows_ CMake but it might work.  that strategy works on linux cmake / C++ usually at least.
 * see if there's a way to have `conda` and `vcpkg` work together for `pycolmap` windows wheels.. https://github.com/conda-forge/vcpkg-feedstock  I guess most windows users use conda?  And so that might be a fruitful avenue.

**Comment by pwais** [comment]
cc https://github.com/colmap/pycolmap/issues/70

**Comment by maorp** [comment]
https://github.com/colmap/pycolmap/pull/85/files 
this worked for me, just use: vcpkg install colmap[cuda]:x64-windows --head
if you want to use dense reconstruction...

if vcpkg fails to build with cuda (nvcc errors) - there is another way...

1. install colmap without cuda using vcpkg (this will also install all deps)
2. compile colmap independently from source using cmake (with cuda)
3. copy the libs from 3 to vcpkg installed/colmap folder
4. if you want to build pycolmap from source - go to C:\dev\vcpkg\installed\x64-windows\share\colmap\colmapConfig.cmake find the line with "set(COLMAP_CUDA_ENABLED ON)" - make sure its on.
5. add env variable CMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake
6. in pycolmap folder - pip install .

**Comment by osama-swe** [comment]
> +1, likely the source of some issues/confusions when installing hloc: [cvg/Hierarchical-Localization#149](https://github.com/cvg/Hierarchical-Localization/issues/149) [cvg/Hierarchical-Localization#140](https://github.com/cvg/Hierarchical-Localization/issues/140)

Hello, yes I've cloned this repo but cant run because i can't install pycolmap. Any ideas on how to solve? I'm on Windows

**Comment by sarlinpe** [comment]
We now have [instructions to build PyCOLMAP on Windows](https://github.com/colmap/pycolmap/tree/sarlinpe/windows-ci#building-from-source). We also have pre-built wheels that are available [here](https://github.com/colmap/pycolmap/actions/runs/7286946343) and can be installed with pip. I don't have a Windows machine at hand so it'd be great if someone could confirm that they work. We'll then release them on PyPI.

**Comment by sarlinpe** [comment]
I'm closing this issues now that we have on PyPI wheels for Windows. We also have instructions for building pycolmap from vcpkg dependencies. Feel free to open a new issue in case you run into any trouble.
